#!/usr/bin/env python3
import os
import base64

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DOCS_ROOT = os.path.dirname(SCRIPT_DIR)
MUSIC_DIR = os.path.join(DOCS_ROOT, 'music')
OUT_JS = os.path.join(DOCS_ROOT, 'assets', 'js', 'audio-data.js')

entries = []
for fn in sorted(os.listdir(MUSIC_DIR)):
    if not fn.lower().endswith('.mp3'):
        continue
    path = os.path.join(MUSIC_DIR, fn)
    with open(path, 'rb') as f:
        b = f.read()
    b64 = base64.b64encode(b).decode('ascii')
    key = 'music/' + fn
    uri = 'data:audio/mpeg;base64,' + b64
    entries.append((key, uri))

with open(OUT_JS, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by tools/embed_audio.py\n')
    f.write('// Provides a mapping of local music paths to data-URI strings for use when the page is opened via file://\n')
    f.write('window.EMBEDDED_AUDIO = window.EMBEDDED_AUDIO || {};\n')
    f.write(' (function() {\n')
    f.write('  var m = {};\n')
    for key, uri in entries:
        f.write("  m['%s'] = '%s';\n" % (key.replace("'", "\\'"), uri))
    f.write("  for (var k in m) if (m.hasOwnProperty(k)) window.EMBEDDED_AUDIO[k] = m[k];\n")
    f.write('})();\n')

print('Wrote', OUT_JS)
print('Entries:', len(entries))
